DROP TABLE IF EXISTS users CASCADE;

CREATE SEQUENCE IF NOT EXISTS serial START 100000000;

CREATE TABLE users (
  id INTEGER PRIMARY KEY NOT NULL DEFAULT nextval('serial'),
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);